Backend/Controllers/FileController.cs, Backend/Data/DataContext.cs, Backend/Models/Book.cs, Backend/Models/User.cs, Backend/Models/UserBookRecord.cs, Backend/Program.cs, Backend/Repositories/BooksRepository.cs, Backend/Repositories/RefreshTokenRepository.cs, Backend/Repositories/UserBookRecordRepository.cs, Backend/Repositories/UserRepository.cs, Backend/Services/AuthService.cs, Backend/Services/FileService.cs
This pull request introduces several changes to the backend, primarily focusing on adding support for books and user book records, as well as enhancing file upload functionality. The most important changes include adding new models and repositories, updating existing services and controllers, and modifying the database context.
=> Process csv file and add books to db.

Backend/Services/AuthService.cs
This pull request includes a significant update to the authentication logic in the `AuthService` class. The most important changes focus on replacing the placeholder authentication logic with a more secure implementation that verifies the user's credentials against stored data.
=> Implement real authentication logic in AuthService

Backend/Controllers/AuthController.cs, Backend/Repositories/RefreshTokenRepository.cs, Backend/Repositories/UserRepository.cs, Backend/Services/AuthService.cs
This pull request focuses on improving the asynchronous handling of various methods in the backend services and repositories. The main changes involve updating methods to use asynchronous programming patterns to enhance performance and responsiveness.
=> Asynchronous handling of various methods in the backend services and repositories.

Backend/Models/UserBookRecord.cs, Backend/Repositories/UserBookRecordRepository.cs, Backend/Services/FileService.cs
This pull request fixes a bug in the `Backend` project.
=> Bug fix existing book

Backend/Controllers/StatisticsController.cs, Backend/DTO/BookDetailsDTO.cs, Backend/DTO/StatisticsReadBooksDTO.cs, Backend/DTO/StatisticsReadingProgressDTO.cs, Backend/DTO/StatisticsSummaryDTO.cs, Backend/Models/UserBookRecord.cs, Backend/Program.cs, Backend/Repositories/UserBookRecordRepository.cs, Backend/Services/FileService.cs, Backend/Services/IStatisticsService.cs, Backend/Services/StatisticsService.cs
This pull request introduces a new `StatisticsController` and related services, DTOs, and repository methods to provide various statistical summaries for users. The most important changes include the creation of the `StatisticsController`, the addition of new DTOs for statistics, updates to the `UserBookRecordRepository` to support statistical queries, and the implementation of the `StatisticsService`.
=> Basic statistics

frontend/package-lock.json, frontend/package.json, frontend/src/components/Auth/RegisterForm.tsx, frontend/src/components/Button/InputFileButton.tsx, frontend/src/components/Layout/NavBar.tsx, frontend/src/pages/Books.tsx, frontend/src/pages/Home.tsx, frontend/src/routes/ProtectedRoute.tsx, frontend/src/routes/index.tsx, frontend/src/services/apiClient.ts, frontend/src/services/fileService.ts
This pull request includes several changes to the frontend codebase, focusing on adding new features, updating dependencies, and refactoring existing components. The most important changes include the addition of a file upload component, enhancements to the navigation bar, and updates to the authentication flow.
=> Navbar improvement and upload button.

Backend/Controllers/StatisticsController.cs, Backend/DTO/MonthlyStats.cs, Backend/Repositories/UserBookRecordRepository.cs, Backend/Services/IStatisticsService.cs, Backend/Services/StatisticsService.cs, frontend/package-lock.json, frontend/package.json, frontend/src/components/Card/SummaryStatsCard.tsx, frontend/src/components/Chart/MonthlyAddedBookCountPerYear.tsx, frontend/src/components/Chart/MonthlyCountChart.tsx, frontend/src/components/Chart/MonthlyReadBookCountPerYear.tsx, frontend/src/components/Chart/MonthlyReadPageCountPerYear.tsx, frontend/src/components/Chart/YearlyAddedBookCount.tsx, frontend/src/components/Chart/YearlyCountChart.tsx, frontend/src/components/Chart/YearlyReadBookCount.tsx, frontend/src/components/Chart/YearlyReadPageCount.tsx, frontend/src/context/AuthContext.tsx, frontend/src/pages/Books.tsx, frontend/src/pages/Statistics.css, frontend/src/pages/Statistics.tsx, frontend/src/routes/index.tsx, frontend/src/services/statisticService.ts
This pull request introduces several new endpoints to the `StatisticsController`, adds a new `MonthlyStats` DTO, and updates various services and repositories to support new statistics functionalities. Additionally, this PR integrates frontend components that display various charts and visualizations, accessible via the /statistics page. These charts provide insights such as monthly book readings and yearly statistics.
=> Basic stats.

frontend/src/components/Chart/BookCount.tsx, frontend/src/pages/Statistics.tsx
This pull request introduces a new `BookCount` component to the statistics page of the frontend application. The changes include the creation of the `BookCount` component, its integration into the `Statistics` page, and the necessary imports.
=> Add book count chart.

frontend/src/pages/BookDetail.tsx
This pull request includes significant changes to the `BookDetail` component in `frontend/src/pages/BookDetail.tsx`. The changes involve adding Material-UI components for better UI design, modifying the `Book` interface, and implementing edit functionality for book details.
=> Implement book detail editing functionality with form inputs.

frontend/src/pages/BookDetail.tsx
This pull request includes changes to the `BookDetail` component in the `frontend/src/pages/BookDetail.tsx` file to add book deletion functionality and navigation.
=> Add delete functionality to BookDetail component.

frontend/src/components/Chart/BookCount.tsx, frontend/src/components/Chart/MonthlyCountChart.tsx, frontend/src/components/Chart/YearlyCountChart.tsx, frontend/src/components/Layout/NavBar.tsx, frontend/src/pages/Statistics.tsx
This pull request includes several updates to the frontend components, primarily focusing on improving the layout and structure of the navigation bar, charts, and statistics page. The most important changes include refactoring the `NavBar` component, updating the chart components, and modifying the grid layout in the `Statistics` page.
=> Improved responsive layout.

frontend/package-lock.json, frontend/package.json, frontend/src/components/Layout/NavBar.tsx, frontend/src/pages/DrawBook.tsx, frontend/src/routes/index.tsx
This pull request introduces new dependencies and a new feature for drawing a random book from a user's "to-read" list. The most important changes include updating the `package-lock.json` and `package.json` files with new dependencies, adding a new page for the "DrawBook" feature, and updating the routing to include this new page.
=> Draw book functionality.

Backend.test/Services/AuthServiceTest.cs, Backend.test/Services/BookServiceTest.cs, Backend/Controllers/AuthController.cs, Backend/DTO/LoginRequest.cs, Backend/DTO/LoginResponse.cs, Backend/DTO/RefreshTokenResponse.cs, Backend/DTO/RegisterRequest.cs, Backend/DTO/RegisterResponse.cs, Backend/Data/DataContext.cs, Backend/Interfaces/IAuthService.cs, Backend/Interfaces/IUserRepository.cs, Backend/Models/User.cs, Backend/Program.cs, Backend/Repositories/UserRepository.cs, Backend/Services/AuthService.cs, frontend/src/components/Auth/LoginForm.tsx, frontend/src/components/Auth/RegisterForm.tsx, frontend/src/context/AuthContext.tsx, frontend/src/services/apiClient.ts, frontend/src/services/authService.ts
This pull request includes significant changes to the authentication system, focusing on replacing the use of 'Email' with 'Username' across various components. Additionally, modifications were made to improve the response structures and error handling in the authentication process.
=> Refactor code

Backend/Dockerfile, Backend/Program.cs, Backend/Properties/launchSettings.json, Backend/appsettings.json, docker-compose.yml, frontend/Dockerfile, frontend/src/services/apiClient.ts, frontend/vite.config.ts
This pull request introduces several changes to the backend and frontend Docker configurations, as well as updates to the application settings and startup logic. The most important changes include the addition of Docker support for both backend and frontend, modifications to the backend startup to handle database migrations, and updates to the frontend configuration to support Docker networking.
=> Docker setup

Backend/Controllers/BookController.cs, Backend/DTO/BookDetailsDTO.cs, Backend/Interfaces/IBookService.cs, Backend/Services/BookMapper.cs, Backend/Services/BookService.cs
This pull request includes several changes to the `Backend` project, primarily focused on renaming the `BookDTO` class to `BookDetailsDTO` and refactoring the code to use a new `BookMapper` class for mapping between data transfer objects and models.
=> Add book mapper

Backend/Controllers/StatisticController.cs, Backend/Interfaces/IStatisticService.cs, Backend/Interfaces/IUserStatisticRepository.cs, Backend/Repositories/UserStatisticRepository.cs, Backend/Services/StatisticService.cs, frontend/src/components/Chart/MostReadAuthors.tsx, frontend/src/pages/Statistics.tsx, frontend/src/services/statisticService.ts
This pull request introduces a new feature to display the most-read authors in the statistics section. It includes backend changes to fetch the data and frontend changes to display it in a bar chart.
=> Most read authors chart

Backend/Controllers/BookController.cs, Backend/Interfaces/IBookService.cs, Backend/Services/BookService.cs, frontend/src/pages/Books.tsx, frontend/src/services/bookService.ts
This pull request includes changes to add a feature for deleting all books for a user. The changes span across both the backend and frontend codebases to support this new functionality.
=> Delete all books functionality

Backend/Controllers/AuthController.cs, Backend/Controllers/BookController.cs, Backend/Controllers/ProfileController.cs, Backend/Controllers/StatisticController.cs, frontend/src/components/Auth/LoginForm.tsx, frontend/src/components/Card/BookCard.tsx, frontend/src/components/Card/SummaryStatsCard.tsx, frontend/src/components/Chart/BookCount.tsx, frontend/src/components/Chart/MonthlyAddedBookCount.tsx, frontend/src/components/Chart/MonthlyReadBookCount.tsx, frontend/src/components/Chart/MonthlyReadPageCount.tsx, frontend/src/components/Chart/MostReadAuthors.tsx, frontend/src/components/Chart/YearlyAddedBookCount.tsx, frontend/src/components/Chart/YearlyReadBookCount.tsx, frontend/src/components/Chart/YearlyReadPageCount.tsx, frontend/src/components/Form/AddBookForm.tsx, frontend/src/components/Layout/NavBar.tsx, frontend/src/context/AuthContext.tsx, frontend/src/pages/BookDetail.tsx, frontend/src/pages/Books.tsx, frontend/src/pages/DrawBook.tsx, frontend/src/pages/Profile.tsx, frontend/src/pages/Statistics.tsx, frontend/src/routes/index.tsx, frontend/src/services/bookService.ts, frontend/src/services/profileService.ts, frontend/src/services/statisticService.ts
Enhance clarity and functionality by including userId in route parameters across controllers, components, and services for improved user-specific data handling and navigation.
=> Refactor to include userId in API and routing

frontend/src/components/Card/ProfileCard.tsx, frontend/src/components/Timeline/ActivityTimeline.tsx, frontend/src/pages/Books.tsx, frontend/src/pages/Profile.css, frontend/src/pages/Profile.tsx
This PR improves the user profile page with better navigation options and proper access control restrictions.
=> Profile Page Enhancements and Access Control

Backend/Controllers/ProfileController.cs, frontend/src/components/Card/ProfileCard.tsx, frontend/src/pages/Profile.tsx, frontend/src/services/profileService.ts
Simplify user ID retrieval in the update profile method and streamline the API call. Enhance the ProfileCard component for better profile editing experience and layout. Remove unnecessary bio state from the Profile component.
=> Edit username functionality

Backend/Repositories/UserBookRecordRepository.cs
Adding "Add review" as next activity tracked
=> Add review as another activity
